// <auto-generated />
using ConsumoAlimentario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsumoAlimentario.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230314175134_CreacionTablaAlimento")]
    partial class CreacionTablaAlimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsumoAlimentario.Models.Alimento", b =>
                {
                    b.Property<int>("Alimento_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Alimento_Id"));

                    b.Property<float>("Azucar")
                        .HasColumnType("real");

                    b.Property<float>("Calcio")
                        .HasColumnType("real");

                    b.Property<float>("Calorias")
                        .HasColumnType("real");

                    b.Property<float>("Cantidad")
                        .HasColumnType("real");

                    b.Property<float>("Carbohidratos")
                        .HasColumnType("real");

                    b.Property<float>("Fibra")
                        .HasColumnType("real");

                    b.Property<float>("GrasasTotales")
                        .HasColumnType("real");

                    b.Property<float>("Hierro")
                        .HasColumnType("real");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<float>("Potacio")
                        .HasColumnType("real");

                    b.Property<float>("Proteina")
                        .HasColumnType("real");

                    b.Property<float>("Sodio")
                        .HasColumnType("real");

                    b.Property<float>("VitaminaA")
                        .HasColumnType("real");

                    b.Property<float>("VitaminaC")
                        .HasColumnType("real");

                    b.HasKey("Alimento_Id");

                    b.ToTable("Alimento");
                });
#pragma warning restore 612, 618
        }
    }
}
